#! /bin/sh

killall picom
killall sxhkd
sleep 0.1

sxhkd &
dunst &
nitrogen --restore
xsetroot -cursor_name left_ptr
picom --config ~/.config/picom/picom.conf &
~/.config/polybar/launch.sh
setxkbmap -layout us,ru
setxkbmap -option 'grp:alt_shift_toggle'
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor -d desktop browser games communication creating other terminal

bspc config focus_follows_pointer   true
bspc config border_width            2
bspc config window_gap              0
bspc config normal_border_color     "#75bcff"
bspc config active_border_color     "#d000ff"
bspc config focused_border_color    "#0f8bff"

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop='creating' state=floating follow=on
bspc rule -a Chromium desktop='browser' state=tiled border=off follow=off
bspc rule -a discord desktop='communication' state=tiled border=off follow=off
bspc rule -a Steam desktop='games' state=floating border=off follow=off
bspc rule -a Dolphin desktop='other'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a steam_app_217200 state=fullscreen
bspc rule -a Pavucontrol state=floating
